
CREATE DATABASE bankdb;
USE bankdb;

CREATE TABLE IF NOT EXISTS accounts (
acc_no INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
password VARCHAR(100),
balance DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS transactions (
txn_id INT PRIMARY KEY AUTO_INCREMENT,
acc_no INT,
txn_type VARCHAR(20),
amount DECIMAL(10,2),
txn_date DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (acc_no) REFERENCES accounts(acc_no)
);
 